name: app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  google_generative_ai: ^0.4.6
  flutter_sound: ^9.19.1
  http: ^1.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0

  user_repository:
    path: packages/user_repo

  flashcards_repo:
    path: packages/flashcards_package

  gemini_repo:
    path: packages/gemini_package

  lingva_repo:
    path: packages/lingva_package

  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  bloc: ^8.1.4
  # cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


