// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdQeZbg0W8ZNPk8jxKiin1N4-Q9xZbb9w',
    appId: '1:1034129513889:web:184fc6e724fcbe003a7fe0',
    messagingSenderId: '1034129513889',
    projectId: 'application-c6306',
    authDomain: 'application-c6306.firebaseapp.com',
    storageBucket: 'application-c6306.firebasestorage.app',
    measurementId: 'G-TCF7NW4LF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCByn98BEnxmyBdVHxFN5atQ9MuWe1h1_E',
    appId: '1:1034129513889:android:7db7e22020bce30f3a7fe0',
    messagingSenderId: '1034129513889',
    projectId: 'application-c6306',
    storageBucket: 'application-c6306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0knm27YhXQuVu1IRysD3kQ1885JzxdZU',
    appId: '1:1034129513889:ios:7651acecc737ae623a7fe0',
    messagingSenderId: '1034129513889',
    projectId: 'application-c6306',
    storageBucket: 'application-c6306.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0knm27YhXQuVu1IRysD3kQ1885JzxdZU',
    appId: '1:1034129513889:ios:7651acecc737ae623a7fe0',
    messagingSenderId: '1034129513889',
    projectId: 'application-c6306',
    storageBucket: 'application-c6306.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdQeZbg0W8ZNPk8jxKiin1N4-Q9xZbb9w',
    appId: '1:1034129513889:web:ad4876314063ef933a7fe0',
    messagingSenderId: '1034129513889',
    projectId: 'application-c6306',
    authDomain: 'application-c6306.firebaseapp.com',
    storageBucket: 'application-c6306.firebasestorage.app',
    measurementId: 'G-W4N4QQZY8D',
  );

}